### ISSUE TITLE
How to clear a filter

### ISSUE THREAD

**Issue by Rhobal** [smart-table/smart-table-core#16]
I'm trying to implement a button to clear all filters
Any call to `table.filter()` only seems to add to the table state through `updateTableState() `> `safeAssign()`.

I also observe that when the filter contents are deleted in smart-table-ng, the filter remains as "include empty string". So the only method to clear the filter seems to be to read table state and set all attributes that are already filtered to an "include empty string" filter.

Would the api need a "clear filter" method? The signature could be `clearFilter()` to clear all filters and `clearFilter(pointer)` to clear the filter for one attribute.

**Comment by lorenzofox3** [comment]
you should now be able to clear your filter with 
```javascript
table.filter()
```

**Comment by Rhobal** [comment]
with table.filter() I can clear the whole filter, and with filterDirective.filter() I can clear one filter but only if none other is set. If two filters are set, I cannot reset one of them with filterDirective.filter().

Here is a failing test:
```javascript
test('table directive: filter should partially reset state if one filter is cleared', t => {
    const table = tableFactory({
        tableState: {
            'sort': {},
            'slice': {'page': 1},
            'filter': {'foo': [{'value': 'bar'}], 'baz': [{'value': 'qux'}]},
            'search': {}
        }
    });
    const fd = filterDirective({table, pointer: 'foo'});
    fd.filter(); //should remove foo from filtering, but filter is unchanged
    t.eq(table.getTableState(), {
        sort: {},
        slice: {page: 1},
        filter: {'baz': [{'value': 'qux'}]},
        search: {}
    });
});
```
And the same test split to test the filter directive and the table directive separately

This test for filterDirective works

```javascript
test('filter directive should reset the clauses for the prop when no argument is provided, leaving other clauses alone', t => {
    const table = fakeTable({
        filter: {woot: [{value: 'blah'}], 'foo': [{'value': 'bar'}]}
    });
    const fd = filter({table, pointer: 'woot'});
    const arg = fd.filter();
    t.deepEqual(arg, {'foo': [{'value': 'bar'}]});
});
```
But trying to apply that state to the table fails
```javascript
test('table directive: filter should partially reset state if reduced filter is provided', t => {
    const table = tableFactory({
        tableState: {
            'sort': {},
            'slice': {'page': 1},
            'filter': {'foo': [{'value': 'bar'}], 'baz': [{'value': 'qux'}]},
            'search': {}
        }
    });
    table.filter({'baz': [{'value': 'qux'}]});
    t.eq(table.getTableState(), {
        sort: {},
        slice: {page: 1},
        filter: {'baz': [{'value': 'qux'}]},
        search: {}
    });
});
```
