### ISSUE TITLE
Are there plans for an Angular binding?

### ISSUE THREAD

**Issue by alexgoldstone** [smart-table/smart-table-core#2]
I have seen there is a placeholder project for smart-table-ng2 but Angular isn't mentioned on the homepage which suggests no current binding?

**Comment by lorenzofox3** [comment]
If demands raise from many people or I get a sponsorship for that task yes, but I have to admit this is not my top one priority. Cheers

**Comment by AVE-cesar** [comment]
+1

**Comment by igorlino** [comment]
+1

**Comment by alexzubiaga** [comment]
+1

**Comment by wtczk** [comment]
+1

**Comment by jsmith39** [comment]
+1
When working with AngularJS, the original Smart-table was/is BY FAR my favorite way of handling data.  My company is now moving forward with the new Angular (v5 currently) and I'm really missing having smart-table in my bag of tools.

**Comment by lorenzofox3** [comment]
@jsmith39 
Great to hear that. However I am a bit short of time right now. Do you think you company would be willing to sponsor the development of this module ?

**Comment by lorenzofox3** [comment]
A wrapper for Angular has been implemented: [smart-table-ng](https://github.com/smart-table/smart-table-ng)

**Comment by igorlino** [comment]
Thanks a lot !

Maybe the integration could be listed in the website:
https://smart-table.github.io/www/dist/

otherwise people won't find it.
