### ISSUE TITLE
How can i refresh data source after initialization?

### ISSUE THREAD

**Issue by ganni** [smart-table/smart-table-core#3]
Hi! 

is there any way to refresh overall data source once smartTable instance is initialized? 

Thank you :)

**Comment by lorenzofox3** [comment]
Can you elaborate on the question, I don't really understand ?
With an example would be good ;)

**Comment by ganni** [comment]
Right now I'm creating smart-table instance once I received dataset from server. However once user re-queries the data from server I have to re create smart-table instance all over again with registration of events. I wanted to know if there was any way to just reset data source without re creating?

**Comment by lorenzofox3** [comment]
Ok. You can write a simple extension which replaces your data without changing the data array refference:

```Javascript
const extension = ({tableState, data, table}) => ({
    refresh(newData){
        // empty array without changing ref
        data.splice(0, data.length);
        // add new data (assuming newData is an array)
        data.push(...newData);
        table.exec(); // reapply the current table state
    }
});
```

so you can now instantiate your table.

```Javascript
import stTable from 'smart-table-core'
const table = stTable({data:originalData},extension);

// somewhere
table.refresh(newData);
```
This is the case when you want to update your data with server refresh while keeping the sort,filter,slice logic on the client (ie only on your loaded data).

If you want to move all the logic to your server. You can have a look at [smart-table-server](https://github.com/smart-table/smart-table-server) or at its source code to better understand the logic

**Comment by ganni** [comment]
Thank you lorenzofox3! 

it works like a charm. 

thank you so much for the amazing work!
