### ISSUE TITLE
Supply initial sort, define sort order

### ISSUE THREAD

**Issue by Rhobal** [smart-table/smart-table-core#9]
smart table in angularjs had `st-sort-default="true"` to supply a default sort.
How can I define a default sort? Do I have to `toggle()` until the desired state is reached?
Also I would like to have a method to define the state directly, e.g. by supplying a sort direction to `toggle()`

I'd be willing to contribute, if you can give me some pointers on how you would do it. Increment `hit` until the desired state is reached?

**Comment by lorenzofox3** [comment]
> smart table in angularjs had st-sort-default="true" to supply a default sort.
> How can I define a default sort?

Initial/default values come now from a single source: the initial table state you pass to the table factory.

For Angular, you can see an example on the following [stackblitz](https://stackblitz.com/edit/smart-table-ng-tutorial-2c)

> Also I would like to have a method to define the state directly, e.g. by supplying a sort direction to 

You can directly pass a sort state to [the table sort method ](https://smart-table.github.io/www/dist/table.html) "toggle" method on the sort directive is just for convenience to handle common sequences.

**Comment by Rhobal** [comment]
Thanks, works great!
